// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU52x_C97FGy_bXIdqUeYCKgzlo2aDkZQ',
    appId: '1:543220830396:web:2c88052e97867d2733c0b9',
    messagingSenderId: '543220830396',
    projectId: 'appsothuchi-86913',
    authDomain: 'appsothuchi-86913.firebaseapp.com',
    databaseURL: 'https://appsothuchi-86913-default-rtdb.firebaseio.com',
    storageBucket: 'appsothuchi-86913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBTLHkGQ40KVzneGdHfax1ATeEn0V5qM',
    appId: '1:543220830396:android:4020b4f6961086d133c0b9',
    messagingSenderId: '543220830396',
    projectId: 'appsothuchi-86913',
    databaseURL: 'https://appsothuchi-86913-default-rtdb.firebaseio.com',
    storageBucket: 'appsothuchi-86913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYDY8cTuLZ9Vvc5dmPhiZyi_eTsZLG_4',
    appId: '1:543220830396:ios:3a0d84de4c786e1833c0b9',
    messagingSenderId: '543220830396',
    projectId: 'appsothuchi-86913',
    databaseURL: 'https://appsothuchi-86913-default-rtdb.firebaseio.com',
    storageBucket: 'appsothuchi-86913.firebasestorage.app',
    iosBundleId: 'com.example.nhom1Sothuchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYDY8cTuLZ9Vvc5dmPhiZyi_eTsZLG_4',
    appId: '1:543220830396:ios:3a0d84de4c786e1833c0b9',
    messagingSenderId: '543220830396',
    projectId: 'appsothuchi-86913',
    databaseURL: 'https://appsothuchi-86913-default-rtdb.firebaseio.com',
    storageBucket: 'appsothuchi-86913.firebasestorage.app',
    iosBundleId: 'com.example.nhom1Sothuchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU52x_C97FGy_bXIdqUeYCKgzlo2aDkZQ',
    appId: '1:543220830396:web:e2cce18f4b422c9233c0b9',
    messagingSenderId: '543220830396',
    projectId: 'appsothuchi-86913',
    authDomain: 'appsothuchi-86913.firebaseapp.com',
    databaseURL: 'https://appsothuchi-86913-default-rtdb.firebaseio.com',
    storageBucket: 'appsothuchi-86913.firebasestorage.app',
  );
}
